version: "3.0"

services:

  # Database for development
  mariadb:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=<database_name>
    ports:
      - 3306:3306

  # App
  appname:
    image: <image_name>/dev:0.1
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - mariadb
    depends_on:
      - mariadb
    tty: true
