services:

    server:
        build:
            dockerfile: ./dev/nginx/Dockerfile
        ports:
            - '3000:80'
        volumes:
            - ./dev/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - /var/www/html/vendor
            - ./app:/var/www/html

    app:
        build:
            dockerfile: ./dev/php/Dockerfile
        volumes:
            - ./dev/php/config/php.ini:/usr/local/etc/php/php.ini
            - ./app:/var/www/html
            - ./app/src/core/database/sqlite:/var/www/data
        command: sh -c "composer install && php-fpm"
