version: "3.8"

services:

  # Database for development
  mariadb:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=iwondb
    ports:
      - 3306:3306

  # App
  app:
    image: iwuon:v1.0
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - mariadb
    depends_on:
      - mariadb
    tty: true
