version: "3.0"

services:
  mysql:
    image: mariadb:10.4.31
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=app
    ports:
      - 3306:3306
  app:
    image: app/stable:1.0
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - mysql
    depends_on:
      - mysql
    tty: true
